### ISSUE TITLE
Ensure that the old application starts up on every team member's computer

### ISSUE THREAD

**Issue by Tiernebre** [BoiseState/interfaith-donation#1]
Use the old project repository to build and start up the old applications. Instructions are located at https://github.com/BoiseState/interfaith-sanctuary/blob/master/CharityServer/Project_Config_README.md and https://github.com/BoiseState/interfaith-sanctuary/blob/master/CharityServer/Tomcat_Setup_README.md.

When finished setting up, please leave an image of the application running on the comments below and check your name off the list below.

**Acceptance Criteria:**
- [ ] Every member of Diffused Code will be able to start the Java Spring app, Ionic App, and Postgres without any issues

**Completed Task:**
- [x] Brendan
- [x] Greg 
- [x] Terrence
- [x] Amy

**Comment by Tiernebre** [comment]
![image](https://user-images.githubusercontent.com/20584068/35126857-8eb51f90-fc6c-11e7-9997-c641740c8050.png)

**Comment by gbrasier** [comment]
I have the admin tool and app working.
![setupscreenshot](https://user-images.githubusercontent.com/23016207/35191258-b655d6d4-fe33-11e7-83c1-07256935b324.png)

**Comment by TerrenceWiseman** [comment]
![image](https://user-images.githubusercontent.com/18074783/35199477-64ebab56-febb-11e7-9345-602c90c7c21f.png)
![ifs_initial_setup](https://user-images.githubusercontent.com/18074783/35198727-630e47b8-feb0-11e7-91e1-903401310721.PNG)

not sure why but my pgadmin tool returns fatal errors now. was able to get tables created and see users but only one time.

**Comment by amyfeiling** [comment]
![image](https://user-images.githubusercontent.com/31660029/35202633-0f0f20ac-fee1-11e7-8294-08009f08ccae.png)

**Comment by AdhikariChandra** [comment]
![interfaith screenshot](https://user-images.githubusercontent.com/17534110/35761667-71f64874-0848-11e8-9ff9-0eaed1c5c3f7.JPG)
