### ISSUE TITLE
Move old Ionic project to the new project folder

### ISSUE THREAD

**Issue by Tiernebre** [BoiseState/interfaith-donation#11]
**This task depends upon the completion of task https://github.com/BoiseState/interfaith-donation/issues/7**

The old Ionic project will need to be moved to the new, v3.9+ version of Ionic.

**Acceptance Criteria:**
- [x] The src folder from the old project is now in the new project folder.
- [x] The project runs and looks like the old project's version.

**Comment by IronGrillman** [comment]
Instead of migrating the old Ionic front end, the team has decided to rebuild this section of the application from scratch using Ionic v3.9+
