### ISSUE TITLE
Prettier.js changing single quotes to double quotes

### ISSUE THREAD

**Issue by timwilson139** [BoiseState/interfaith-donation#151]
Prettier is changing the single quotes in front-end-admin/src/main.js to double quotes. This breaks the code.

**Comment by Tiernebre** [comment]
Change implemented in commit: https://github.com/BoiseState/interfaith-donation/commit/b1597c08ebe7c8452eaa9bbf261aa79c0d38dd7a . No pull request as this was an urgent fix that needed to be made
