### ISSUE TITLE
Database Refactor - User Table

### ISSUE THREAD

**Issue by TylerNicholls** [BoiseState/interfaith-donation#160]
User Columns
*user_id
*user_email
*user_password
*user_permission
*user_active

**Acceptance Criteria:**
- [x] The above columns are made using proper PostgresSQL syntax in the mock data tables file.
- [x] A mock file for generated the mock data for users is created on [Mockaroo](https://www.mockaroo.com/).
- [x] The new database table works and you are able to see the mock data, either via Data Grip or through using the Postgres Docker.

**Comment by AdhikariChandra** [comment]
User table is ready. Closing this issue.
