### ISSUE TITLE
Database Refactor - Donor Table

### ISSUE THREAD

**Issue by TylerNicholls** [BoiseState/interfaith-donation#161]
Donor Attributes:
*donor_id
*donor_address
*donor_phone_no
*user_id (foreign key)

**Acceptance Criteria:**
- [x] The above columns are made using proper PostgresSQL syntax in the mock data tables file.
- [x] A mock file for generated the mock data for users is created on [Mockaroo](https://www.mockaroo.com/).
- [x] The new database table works and you are able to see the mock data, either via Data Grip or through using the Postgres Docker.

**Comment by francisbetikoetxea** [comment]
Because #188 has been merged containing the new mock file and fulfills the criteria for this issue, I am closing it.
