### ISSUE TITLE
Refactor Spring Data - Need Model

### ISSUE THREAD

**Issue by Tiernebre** [BoiseState/interfaith-donation#168]
Per the new database schema design on https://github.com/BoiseState/interfaith-donation/issues/163, the need model has been changed and we will have to change our model file to use the new columns.

**Acceptance Criteria:**
- [x] Map all the current need model instance variables to the new columns.
- [x] Instead of using names like "need_create_date" for the instance variables, use "createDate" so it better matches the Java syntax. So remove the need_ and make the variable camel case.

**Comment by francisbetikoetxea** [comment]
Since #178 has been merged and fulfills the criteria listed in this issue, I believe we can close it.
