### ISSUE TITLE
Connect callouts to drop-down selector

### ISSUE THREAD

**Issue by gbrasier** [BoiseState/interfaith-donation#223]
- [x] Individual callouts show up in the Callout selector on the home page.

NOTE: Code from branch 102 could be used as an example on how to access individual callouts and add it to the the front end.

**Comment by gbrasier** [comment]
Paired programmed with @IronGrillman.

**Comment by IronGrillman** [comment]
Retrieves and renders callout id from MockJson file to the dropdown selector on client front end. Functionality will need to be updated to pull callout data from database / API in issue #273.
