### ISSUE TITLE
Ensure CRUD operations work on User

### ISSUE THREAD

**Issue by TylerNicholls** [BoiseState/interfaith-donation#228]
All Crud operations should be available to test on callout and user. 

User
- [x] Create
- [x] Read
- [x] Update
- [x] Delete

**Comment by AdhikariChandra** [comment]
createUser() is working with JSON object without "id" field. See issue #74

**Comment by AdhikariChandra** [comment]
See issue #74 for creating USER - done
See pull request 278 - done
Closing this issue
