### ISSUE TITLE
Unable to Create a User

### ISSUE THREAD

**Issue by TerrenceWiseman** [BoiseState/interfaith-donation#240]
When creating a new Need, the following error message is returned  [ "message": "could not execute statement; SQL [n/a]; constraint [users_pkey]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement" ]

**Comment by AdhikariChandra** [comment]
This issue was due to docker cache - do docker-compose down and it will be resolved. Also, a donor needs to be deleted before a user can be deleted.
